SERVICE_TAXONOMY: dict[str, list[str]] = {
    "Beauty & Wellness": [
        "Waxing Specialist",
        "Facial Esthetician",
        "Manicure/Pedicure Artist",
        "Threading & Brow Shaping",
        "Hair Stylist",
        "Massage Therapist",
        "Laser Technician",
        "Makeup Artist",
        "Bleach & Detan Expert",
        "Hydra-Facialist",
    ],
    "Appliance Repair & Maintenance": [
        "AC Foam-Jet Technician",
        "HVAC Repair",
        "Refrigerator Specialist",
        "Washing Machine Repair",
        "Water Purifier (RO) Specialist",
        "Microwave & OTG Technician",
        "Kitchen Chimney Specialist",
        "Geyser/Water Heater Repair",
        "Television Technician",
        "Laptop & Mobile Repair",
    ],
    "Home Cleaning & Pest Control": [
        "Deep Cleaning Professional",
        "Party Cleaners",
        "Bathroom Sanitation Specialist",
        "Kitchen Degreasing",
        "Sofa & Carpet Shampooing",
        "Pest Control Operator",
        "Disinfection Specialist",
        "Mattress Cleaning",
        "Full Home Deep Clean",
        "Wall & Ceiling Cleaning",
        "Window & Mesh Cleaning",
    ],
    "Handyman & Home Improvement": [
        "Electrician",
        "Plumber",
        "Plumbers",
        "Carpenter",
        "Wall Painter",
        "Waterproofing Expert",
        "Smart Home Installer",
        "Drill & Hang Specialist",
        "Floor Polisher",
        "Door & Window Specialist",
        "Tiler",
    ],
    "New & Niche Services": [
        "Native Product Consultant",
        "InstaHelp Responder",
        "Wedding Helpers",
        "Home Cook",
        "Gardener",
        "Gardening Specialist",
        "Elder Care Assistant",
        "Driver on Demand",
        "Drivers",
        "Moving Assistance",
        "Packers & Movers",
        "Packers",
        "Security Guard",
        "Receptionist",
        "Furniture Restoration",
        "Visual Consultant",
        "Air Purifier Technician",
    ],
}

ALL_SERVICES = {service for services in SERVICE_TAXONOMY.values() for service in services}
